#!/usr/bin/env bash
# setup.sh — Interactive setup for Look4Gold13 API keys and configuration
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/.config"

echo "========================================="
echo "  Look4Gold13 — Setup"
echo "  NIST AU-13 Information Disclosure Monitor"
echo "========================================="
echo

# --- Check dependencies ---
echo "Checking required dependencies..."
missing=()
for cmd in curl jq; do
    if command -v "$cmd" &>/dev/null; then
        echo "  [OK] $cmd"
    else
        echo "  [MISSING] $cmd"
        missing+=("$cmd")
    fi
done

if (( ${#missing[@]} > 0 )); then
    echo
    echo "ERROR: Missing required dependencies: ${missing[*]}"
    echo "Install them with: sudo apt install ${missing[*]}"
    exit 1
fi
echo

# Optional dependencies for the CSE scraper (ENABLE_CSE_SCRAPE=true).
# Missing these is OK — the scraper just stays disabled until the user
# installs them and flips the flag.
echo "Checking optional CSE scraper dependencies..."
cse_chromium_ok=false
for cmd in chromium chromium-browser google-chrome; do
    if command -v "$cmd" &>/dev/null; then
        echo "  [OK] $cmd"
        cse_chromium_ok=true
        break
    fi
done
if [[ "$cse_chromium_ok" == "false" ]]; then
    echo "  [MISSING] chromium — needed only for CSE scraper (optional)"
    echo "             install: sudo apt install chromium-browser   OR   snap install chromium"
fi
if command -v pup &>/dev/null; then
    echo "  [OK] pup"
    cse_pup_ok=true
else
    cse_pup_ok=false
    echo "  [MISSING] pup — needed only for CSE scraper (optional)"
    echo "             install: go install github.com/ericchiang/pup@latest"
    echo "             or download: https://github.com/ericchiang/pup/releases"
fi
echo

# --- API key prompts ---
apis_file="$CONFIG_DIR/apis.conf"

# Load existing keys if present
BRAVE_API_KEY=""
TAVILY_API_KEY=""
NIST_API_KEY=""
OTX_API_KEY=""
XAI_API_KEY=""
CSE_ID=""
ENABLE_CSE_SCRAPE="false"
if [[ -f "$apis_file" ]]; then
    # shellcheck source=/dev/null
    source "$apis_file"
    echo "Existing apis.conf found. Leave a field blank to keep the current value."
    echo
fi

prompt_key() {
    local name="$1"
    local current="$2"

    if [[ -n "$current" ]]; then
        local masked="${current:0:4}...${current: -4}"
        # Use -s to hide API key input from terminal (and shell history via subshell)
        read -rsp "  $name [$masked] (Enter to keep): " value
        echo >&2  # newline after silent input
        if [[ -z "$value" ]]; then
            printf '%s' "$current"
        else
            printf '%s' "$value"
        fi
    else
        read -rsp "  $name (Enter to skip): " value
        echo >&2  # newline after silent input
        printf '%s' "$value"
    fi
}

echo "Enter your API keys (press Enter to skip or keep existing):"
echo
echo "  Brave Search API — https://brave.com/search/api/"
BRAVE_API_KEY=$(prompt_key "BRAVE_API_KEY" "$BRAVE_API_KEY" "Brave Search")
echo
echo "  Tavily Search API — https://app.tavily.com/home"
TAVILY_API_KEY=$(prompt_key "TAVILY_API_KEY" "$TAVILY_API_KEY" "Tavily Search")
echo
echo "  NIST NVD API — https://nvd.nist.gov/developers/request-an-api-key"
NIST_API_KEY=$(prompt_key "NIST_API_KEY" "$NIST_API_KEY" "NIST NVD")
echo
echo "  AlienVault OTX API — https://otx.alienvault.com/api"
OTX_API_KEY=$(prompt_key "OTX_API_KEY" "$OTX_API_KEY" "AlienVault OTX")
echo
echo "  xAI (Grok) API — https://console.x.ai/"
XAI_API_KEY=$(prompt_key "XAI_API_KEY" "$XAI_API_KEY" "xAI Grok")
echo

# --- Google Programmable Search Engine (CSE) scraper ---
echo "Google Programmable Search Engine scraper (optional)"
echo "  The Google Custom Search JSON API was deprecated. This tool can"
echo "  scrape the public CSE widget using headless chromium + pup instead."
echo "  Create a CSE at: https://programmablesearchengine.google.com/"
echo

# CSE_ID is NOT sensitive — use plain read, not read -rs.
if [[ -n "$CSE_ID" ]]; then
    read -rp "  CSE_ID (cx) [$CSE_ID] (Enter to keep): " _cse_input
    CSE_ID="${_cse_input:-$CSE_ID}"
else
    read -rp "  CSE_ID (cx, Enter to skip): " CSE_ID
fi

if [[ -n "$CSE_ID" ]]; then
    # Only enable if both optional deps are present
    if [[ "$cse_chromium_ok" == "true" && "$cse_pup_ok" == "true" ]]; then
        read -rp "  Enable CSE scraper now? [${ENABLE_CSE_SCRAPE}] (true/false, Enter to keep): " _cse_enable
        _cse_enable="${_cse_enable:-$ENABLE_CSE_SCRAPE}"
        if [[ "$_cse_enable" == "true" || "$_cse_enable" == "false" ]]; then
            ENABLE_CSE_SCRAPE="$_cse_enable"
        fi
    else
        echo "  [INFO] chromium and/or pup are missing — CSE scraper will stay disabled"
        echo "         until you install them and set ENABLE_CSE_SCRAPE=true in apis.conf."
        ENABLE_CSE_SCRAPE="false"
    fi
fi
echo

# Write apis.conf
cat > "$apis_file" <<EOF
# Look4Gold13 API Keys (auto-generated by setup.sh)
# DO NOT commit this file to version control.

BRAVE_API_KEY="$BRAVE_API_KEY"
TAVILY_API_KEY="$TAVILY_API_KEY"
NIST_API_KEY="$NIST_API_KEY"
OTX_API_KEY="$OTX_API_KEY"
XAI_API_KEY="$XAI_API_KEY"

# Google Programmable Search Engine scraper (see docs above)
ENABLE_CSE_SCRAPE="$ENABLE_CSE_SCRAPE"
CSE_ID="$CSE_ID"
EOF
chmod 600 "$apis_file"
chmod 700 "$CONFIG_DIR" 2>/dev/null || true
echo "API keys saved to $apis_file"

# --- Keywords file ---
keywords_file="$CONFIG_DIR/keywords.conf"
if [[ ! -f "$keywords_file" ]]; then
    cp "$CONFIG_DIR/keywords.conf.template" "$keywords_file"
    echo "Created $keywords_file from template."
    echo "  -> Edit this file to add your organization's keywords before running a scan."
else
    echo "Keywords file already exists: $keywords_file"
fi
echo

# --- Dorks file ---
dorks_file="$CONFIG_DIR/dorks.conf"
if [[ ! -f "$dorks_file" ]]; then
    cp "$CONFIG_DIR/dorks.conf.template" "$dorks_file"
    echo "Created $dorks_file from template."
    echo "  -> Edit this file to customize search dorks for your threat profile."
else
    echo "Dorks file already exists: $dorks_file"
fi
echo

# --- Validate API keys ---
echo "Validating API keys..."

if [[ -z "$BRAVE_API_KEY" ]]; then
    echo "  [SKIP] Brave Search — no key provided"
elif curl -sf --max-time 15 --max-redirs 3 --proto =https \
    -H "X-Subscription-Token: $BRAVE_API_KEY" \
    "https://api.search.brave.com/res/v1/web/search?q=test&count=1" &>/dev/null; then
    echo "  [OK]   Brave Search"
else
    echo "  [FAIL] Brave Search — key may be invalid (check manually)"
fi

if [[ -z "$TAVILY_API_KEY" ]]; then
    echo "  [SKIP] Tavily Search — no key provided"
elif curl -sf --max-time 15 --max-redirs 3 --proto =https \
    -X POST -H "Content-Type: application/json" \
    -H "Authorization: Bearer $TAVILY_API_KEY" \
    -d '{"query":"test","max_results":1}' \
    "https://api.tavily.com/search" &>/dev/null; then
    echo "  [OK]   Tavily Search"
else
    echo "  [FAIL] Tavily Search — key may be invalid (check manually)"
fi

if [[ -z "$NIST_API_KEY" ]]; then
    echo "  [SKIP] NIST NVD — no key provided"
elif curl -sf --max-time 15 --max-redirs 3 --proto =https \
    -H "apiKey: $NIST_API_KEY" \
    "https://services.nvd.nist.gov/rest/json/cves/2.0?keywordSearch=test&resultsPerPage=1" &>/dev/null; then
    echo "  [OK]   NIST NVD"
else
    echo "  [FAIL] NIST NVD — key may be invalid (check manually)"
fi

if [[ -z "$OTX_API_KEY" ]]; then
    echo "  [SKIP] AlienVault OTX — no key provided"
elif curl -sf --max-time 15 --max-redirs 3 --proto =https \
    -H "X-OTX-API-KEY: $OTX_API_KEY" \
    "https://otx.alienvault.com/api/v1/user/me" &>/dev/null; then
    echo "  [OK]   AlienVault OTX"
else
    echo "  [FAIL] AlienVault OTX — key may be invalid (check manually)"
fi

if [[ -z "$XAI_API_KEY" ]]; then
    echo "  [SKIP] xAI (Grok) — no key provided"
elif curl -sf --max-time 15 --max-redirs 3 --proto =https \
    -H "Authorization: Bearer $XAI_API_KEY" \
    "https://api.x.ai/v1/models" &>/dev/null; then
    echo "  [OK]   xAI (Grok)"
else
    echo "  [FAIL] xAI (Grok) — key may be invalid (check manually)"
fi

echo

# --- 4chan Archive Search ---
echo "4chan Archive Search (via web search dorks)"
echo "  Searches indexed 4chan archive pages using site: dork queries."
echo "  Requires a Brave or Tavily API key."

# Load current setting if settings.conf exists
_fourchan_current="${FOURCHAN_ENABLED:-true}"
if [[ -f "$CONFIG_DIR/settings.conf" ]]; then
    _fourchan_current=$(grep '^FOURCHAN_ENABLED=' "$CONFIG_DIR/settings.conf" 2>/dev/null | cut -d= -f2 | tr -d '"' || echo "true")
fi
[[ -z "$_fourchan_current" ]] && _fourchan_current="true"

read -rp "  Enable 4chan archive search? [${_fourchan_current}] (true/false, Enter to keep): " _fourchan_input
_fourchan_input="${_fourchan_input:-$_fourchan_current}"
if [[ "$_fourchan_input" == "true" || "$_fourchan_input" == "false" ]]; then
    sed -i "s/^FOURCHAN_ENABLED=.*/FOURCHAN_ENABLED=${_fourchan_input}/" "$CONFIG_DIR/settings.conf" 2>/dev/null || true
    echo "  [OK] 4chan archive search: $_fourchan_input"
else
    echo "  [SKIP] Invalid input, keeping current value: $_fourchan_current"
fi
echo

# --- Make main script executable ---
chmod +x "$SCRIPT_DIR/look4gold.sh" 2>/dev/null || true
echo "Setup complete. Run: bash look4gold.sh --help"
